#!/usr/bin/env php
<?php

require __DIR__ . '/vendor/autoload.php';


use Ofcold\LuminousSMS\LuminousSMS;
use Ofcold\LuminousSMS\Helpers;
use Ofcold\LuminousSMS\Contracts\MessageInterface;

$sms = new LuminousSMS(include __DIR__ . '/resources/config/sms.php');

$result = $sms->sender(function($messager) {
	$messager
		->setMobilePhone('18898726543')
		->setType(Ofcold\LuminousSMS\Contracts\MessageInterface::VOICE_MESSAGE)
		->setContent('您的验证码是{code}, 验证码将在2分钟后失效！请及时使用。')
		->setPaserData(['code'	=> rand(1000, 9999)]);
});

var_dump($result);